name: Env Vars
'on':
  push:
    branches:
      - main
jobs:
  create-envfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_REACT_APP_FIREBASE_API_KEY: ${{ secrets.admin.REACT_APP_FIREBASE_API_KEY }}
          envkey_REACT_APP_FIREBASE_PROJECT_ID: ${{ secrets.admin.REACT_APP_FIREBASE_PROJECT_ID }}
          envkey_REACT_APP_FIREBASE_SENDER_ID: ${{ secrets.admin.APP_FIREBASE_SENDER_ID }}
          envkey_REACT_APP_FIREBASE_APP_ID: ${{ secrets.admin.REACT_APP_FIREBASE_APP_ID }}
          envkey_REACT_APP_FIREBASE_MEASUREMENT_ID: ${{ secrets.admin.REACT_APP_FIREBASE_MEASUREMENT_ID }}
          envkey_REACT_APP_RECAPTCHA_KEY: ${{ secrets.admin.REACT_APP_RECAPTCHA_KEY }}
          envkey_REACT_APP_CLOUDINARY_CLOUD_NAME: ${{ secrets.admin.REACT_APP_CLOUDINARY_CLOUD_NAME }}
          envkey_REACT_APP_CLOUDINARY_KEY: ${{ secrets.admin.REACT_APP_CLOUDINARY_KEY }}
          directory: './'
          file_name: '.env'
